services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: currency-app
    volumes:
      - ./app:/var/www/html
      - ./.env:/var/www/html/.env:ro
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.27
    container_name: currency-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: currency-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: currency-redis
    ports:
      - "6379:6379"

volumes:
  dbdata: